name: Infracost Cost Estimates

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write    # needed to post comments
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init & Plan
        id: plan
        run: |
          terraform init -input=false
          terraform plan -out=tfplan.binary -input=false

      - name: Infracost PR check
        uses: infracost/infracost-gh-action@v1
        with:
          path: .
          terraform_plan_flags: "-no-color tfplan.binary"
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

      - name: Comment PR with cost estimate
        uses: infracost/actions/comment@v2
        with:
          report_path: infracost.json
          update: true